export const scholarProfile = 'https://scholar.google.com.sg/citations?user=4yxo8G0AAAAJ&hl=zh-CN';
export const oldProfile = 'https://gr.xjtu.edu.cn/zqwei/';
export const bookUrl = 'https://shop.elsevier.com/books/delay-doppler-communications-and-sensing/li/978-0-443-26528-0';

export const scholarSearch = (title: string) =>
  `https://scholar.google.com/scholar?q=${encodeURIComponent(`Zhiqiang Wei ${title}`)}`;

export type Publication = { year: string; title: string; venue: string; note?: string; href?: string };

export const underReviewPublications: Publication[] = [
  { year:'2026', title:'Game-Theoretic Multi-Agent Reinforcement Learning for Swarm Trajectory Planning in Low-Altitude Wireless Networks', venue:'arXiv:2606.16386', href:'https://arxiv.org/abs/2606.16386' },
  { year:'2026', title:'OFDM Waveform Optimization for Bistatic Integrated Sensing and Communications', venue:'arXiv:2603.08442', href:'https://arxiv.org/abs/2603.08442' },
  { year:'2025', title:'Hybrid Iterative Detection for OTFS: Interplay between Local L-MMSE and Global Message Passing', venue:'arXiv:2512.14116', href:'https://arxiv.org/abs/2512.14116' },
  { year:'2025', title:'ISAC with Affine Frequency Division Multiplexing: An FMCW-Based Signal Processing Perspective', venue:'arXiv:2511.12308', href:'https://arxiv.org/abs/2511.12308' },
];

export const journalPublications: Publication[] = [
  { year:'2026', title:'Delay-Doppler Domain Signal Processing Aided OFDM (DD-a-OFDM) for 6G and Beyond', venue:'IEEE Transactions on Communications', href:'https://doi.org/10.1109/TCOMM.2026.3706603' },
  { year:'2026', title:'Orthogonal Time Frequency Space Modulation: A Tutorial View on Delay-Doppler Communications via Zak Transform', venue:'IEEE Open Journal of the Communications Society, vol. 7, pp. 6426–6444' },
  { year:'2026', title:'Intelligent Predictive Beamforming for Integrated Sensing, Communication and Power Transfer for Low-Altitude Economy', venue:'IEEE Transactions on Wireless Communications, vol. 25, pp. 17165–17179' },
  { year:'2026', title:'A Novel Symbol Level Precoding-Based AFDM Transmission Framework: Offloading Equalization Burden to Transmitter Side', venue:'IEEE Transactions on Wireless Communications, vol. 25, pp. 17042–17057' },
  { year:'2026', title:'Task-Oriented Integrated Sensing and Communication for Multidevice Cooperative Motion Recognition', venue:'IEEE Transactions on Mobile Computing, vol. 25, no. 7, pp. 11116–11129' },
  { year:'2026', title:'Channel Knowledge Map-Assisted Dual-Domain Tracking and Predictive Beamforming for High-Mobility Wireless Networks', venue:'IEEE Transactions on Wireless Communications, vol. 25, pp. 10968–10985' },
  { year:'2026', title:'Direction-of-Arrival Estimation From a Mixture of Linear and Magnitude-Only Measurements', venue:'IEEE Transactions on Vehicular Technology, vol. 75, no. 2, pp. 3470–3474' },
  { year:'2026', title:'Extended Arimoto-Blahut Algorithms for Bistatic Integrated Sensing and Communications Systems', venue:'Entropy, Jan. 2026' },
  { year:'2025', title:'Code-Length Optimization for Polar-Coded OTFS Modulation via Tensor Decomposition', venue:'IEEE Communications Letters, vol. 29, no. 12, pp. 3058–3062' },
  { year:'2025', title:'Information-Theoretic Limits of Bistatic Integrated Sensing and Communication', venue:'IEEE Transactions on Information Theory, vol. 71, no. 12, pp. 9302–9318' },
  { year:'2025', title:'Downlink-Uplink Collaborative Channel Estimation for TDD Massive MIMO Communications', venue:'IEEE Transactions on Signal Processing, vol. 73, pp. 3614–3628' },
  { year:'2025', title:'AdaptTrack: A Robust Tracking System for Complex Environments Based on WiFi Device Selection Strategy', venue:'Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies, 9(3)' },
  { year:'2025', title:'An Integrated OTFS-NOMA Framework for Multi-Beam LEO Systems: Reliability and Capacity Analysis', venue:'IEEE Transactions on Wireless Communications' },
  { year:'2025', title:'Self-Interference-Alleviated Multi-Beam Steering for On-Demand Sensing and Communication Performance Tradeoff of Full-Duplex ISAC', venue:'IEEE Transactions on Wireless Communications' },
  { year:'2025', title:'Cross-Domain Iterative Detection for OTFS Transmission with Frequency Domain Equalization', venue:'IEEE Transactions on Communications' },
  { year:'2025', title:'Deep Learning-Empowered Secure Predictive Beamforming Design for Integrated Sensing and Communications Systems', venue:'IEEE Transactions on Wireless Communications' },
  { year:'2025', title:'Near Optimal Hybrid Digital-Analog Beamforming for mmWave Point-to-Point MIMO Transmissions Using OTFS Waveforms', venue:'IEEE Transactions on Communications' },
  { year:'2025', title:'RIS-aided MIMO Beamforming: Piecewise Near-field Channel Model', venue:'IEEE Transactions on Communications' },
  { year:'2025', title:'Robust Beamfocusing for Secure NFC with Imperfect CSI', venue:'Sensors, vol. 25, no. 4, 1240' },
  { year:'2025', title:'On Hybrid Detection of Wireless Communications Over Interference Channels: A Generalized Framework', venue:'IEEE Journal on Selected Areas in Communications, vol. 43, no. 4, pp. 1214–1229' },
  { year:'2025', title:'Low-Complexity Minimum BER Precoder Design for ISAC Systems: A Delay-Doppler Perspective', venue:'IEEE Transactions on Wireless Communications, vol. 24, no. 2, pp. 1526–1540' },
  { year:'2025', title:'COFFEE: Covariance Fitting and Focusing for Wideband Direction-of-Arrival Estimation', venue:'IEEE Transactions on Signal Processing, vol. 73, pp. 156–170' },
  { year:'2024', title:'Integrated Sensing and Communication: Who Benefits More?', venue:'ZTE Communications, vol. 22, no. 3, pp. 37–47' },
  { year:'2024', title:'Resource Allocation Design for Next-Generation Multiple Access: A Tutorial Overview', venue:'Proceedings of the IEEE, vol. 112, no. 9, pp. 1230–1263' },
  { year:'2024', title:'Channel Estimation for RIS-Aided MIMO Systems: A Partially Decoupled Atomic Norm Minimization Approach', venue:'IEEE Transactions on Wireless Communications, vol. 23, no. 11, pp. 16048–16061' },
  { year:'2024', title:'Networked Integrated Sensing and Communications for 6G Wireless Systems', venue:'IEEE Internet of Things Journal, vol. 11, no. 17, pp. 29062–29075' },
  { year:'2024', title:'Spatial-Temporal Resource Optimization for Uneven-Traffic LEO Satellite Systems', venue:'IEEE Journal on Selected Areas in Communications, vol. 42, no. 5, pp. 1279–1291' },
  { year:'2024', title:'Toward 6G Multicell Orthogonal Time Frequency Space Systems', venue:'IEEE Vehicular Technology Magazine, vol. 19, no. 1, pp. 55–64' },
  { year:'2024', title:'Integrated Sensing, Navigation, and Communication for Secure UAV Networks with a Mobile Eavesdropper', venue:'IEEE Transactions on Wireless Communications, vol. 23, no. 7, pp. 7060–7078' },
  { year:'2024', title:'Direction-of-Arrival Estimation for Constant Modulus Signals Using a Structured Matrix Recovery Technique', venue:'IEEE Transactions on Wireless Communications, vol. 23, no. 4, pp. 3117–3130' },
  { year:'2023', title:'New Delay Doppler Communication Paradigm in 6G Era: A Survey of Orthogonal Time Frequency Space (OTFS)', venue:'China Communications, vol. 20, no. 6, pp. 1–25', note:'封面文章' },
  { year:'2023', title:'New Reweighted Atomic Norm Minimization Approach for Line Spectral Estimation', venue:'Signal Processing, vol. 206, 108897' },
  { year:'2023', title:'Orthogonal Time Frequency Space Modulation – Part I: Fundamentals and Challenges Ahead', venue:'IEEE Communications Letters, vol. 27, no. 1, pp. 4–8', note:'EiC invited paper' },
  { year:'2023', title:'Orthogonal Time Frequency Space Modulation – Part II: Transceiver Designs', venue:'IEEE Communications Letters, vol. 27, no. 1, pp. 9–13', note:'EiC invited paper' },
  { year:'2023', title:'Orthogonal Time Frequency Space Modulation – Part III: ISAC and Potential Applications', venue:'IEEE Communications Letters, vol. 27, no. 1, pp. 14–18', note:'EiC invited paper' },
  { year:'2022', title:'Resource Allocation and 3D Trajectory Design for Power-Efficient IRS-Assisted UAV-NOMA Communications', venue:'IEEE Transactions on Wireless Communications, vol. 21, no. 12, pp. 10315–10334' },
  { year:'2022', title:'Off-grid Channel Estimation with Sparse Bayesian Learning for OTFS Systems', venue:'IEEE Transactions on Wireless Communications, vol. 21, no. 9, pp. 7407–7426', note:'ESI Highly Cited Paper' },
  { year:'2022', title:'A Novel ISAC Transmission Framework Based on Spatially-Spread Orthogonal Time Frequency Space Modulation', venue:'IEEE Journal on Selected Areas in Communications, vol. 40, no. 6, pp. 1854–1872', note:'JSAC featured article' },
  { year:'2022', title:'Wireless Powered Mobile Edge Computing: Dynamic Resource Allocation and Throughput Maximization', venue:'IEEE Transactions on Mobile Computing, vol. 21, no. 6, pp. 2271–2288' },
  { year:'2022', title:'Faster-than-Nyquist Asynchronous NOMA Outperforms Synchronous NOMA', venue:'IEEE Journal on Selected Areas in Communications, vol. 40, no. 4, pp. 1128–1145' },
  { year:'2022', title:'Cross Domain Iterative Detection for Orthogonal Time Frequency Space Modulation', venue:'IEEE Transactions on Wireless Communications, vol. 21, no. 4, pp. 2227–2242' },
  { year:'2022', title:'Resource Allocation for Simultaneous Wireless Information and Power Transfer Systems: A Tutorial Overview', venue:'Proceedings of the IEEE, vol. 110, no. 1, pp. 127–149' },
  { year:'2022', title:'Genetic Algorithm for Sparse Optimization of Mills Cross Array Used in Underwater Acoustic Imaging', venue:'Journal of Marine Science and Engineering, vol. 10, no. 2' },
  { year:'2021', title:'Integrated Radar Sensing and Communication-assisted Orthogonal Time Frequency Space Transmission for Vehicular Networks', venue:'IEEE Journal of Selected Topics in Signal Processing, vol. 15, no. 6, pp. 1515–1528', note:'JSTSP featured article · ESI Highly Cited Paper' },
  { year:'2021', title:'Channel Estimation and User Identification with Deep Learning for Massive Machine-Type Communications', venue:'IEEE Transactions on Vehicular Technology, vol. 70, no. 10, pp. 10709–10722' },
  { year:'2021', title:'Robust and Secure Sum-Rate Maximization for Multiuser MISO Downlink Systems with Self-sustainable IRS', venue:'IEEE Transactions on Communications, vol. 69, no. 10, pp. 7032–7049', note:'ESI Highly Cited Paper' },
  { year:'2021', title:'Performance Analysis of Coded OTFS Systems over High-Mobility Channels', venue:'IEEE Transactions on Wireless Communications, vol. 20, no. 9, pp. 6033–6048' },
  { year:'2021', title:'Data-Aided Channel Estimation for OTFS Systems with a Superimposed Pilot and Data Transmission Scheme', venue:'IEEE Transactions on Vehicular Technology, vol. 70, no. 9' },
  { year:'2021', title:'Orthogonal Time-Frequency Space Modulation: A Promising Next-Generation Waveform', venue:'IEEE Wireless Communications, vol. 28, no. 4, pp. 136–144', note:'ESI Highly Cited Paper' },
  { year:'2021', title:'Hybrid MAP and PIC Detection for OTFS Modulation', venue:'IEEE Transactions on Vehicular Technology, vol. 70, no. 7, pp. 7193–7198' },
  { year:'2021', title:'Transmitter and Receiver Window Designs for Orthogonal Time Frequency Space Modulation', venue:'IEEE Transactions on Communications, vol. 69, no. 4, pp. 2207–2223' },
  { year:'2021', title:'Sum-Rate Maximization for IRS-Assisted UAV OFDMA Communication Systems', venue:'IEEE Transactions on Wireless Communications, vol. 20, no. 4, pp. 2530–2550' },
  { year:'2021', title:'Two-Tier Communication for UAV-Enabled Massive IoT Systems', venue:'IEEE Journal on Selected Areas in Communications, vol. 39, no. 4, pp. 1132–1146' },
  { year:'2021', title:'Deep Transfer Learning for Signal Detection in Ambient Backscatter Communications', venue:'IEEE Transactions on Wireless Communications, vol. 20, no. 3, pp. 1624–1638' },
  { year:'2021', title:'Location-aware Predictive Beamforming for UAV Communications: A Deep Learning Approach', venue:'IEEE Wireless Communications Letters, vol. 10, no. 3, pp. 668–672' },
  { year:'2020', title:'Joint Trajectory and Resource Allocation Design for Energy-Efficient Secure UAV Communication Systems', venue:'IEEE Transactions on Communications, vol. 68, no. 7, pp. 4536–4553', note:'ESI Highly Cited Paper' },
  { year:'2020', title:'A Simple Variational Bayes Detector for Orthogonal Time Frequency Space (OTFS) Modulation', venue:'IEEE Transactions on Vehicular Technology, vol. 69, no. 7, pp. 7976–7980' },
  { year:'2020', title:'Resource Allocation for Secure Multi-UAV Communication Systems with Multi-Eavesdropper', venue:'IEEE Transactions on Communications, vol. 68, no. 7, pp. 4490–4506' },
  { year:'2020', title:'On the Performance Gain of NOMA over OMA in Uplink Communication Systems', venue:'IEEE Transactions on Communications, vol. 68, no. 1, pp. 536–568', note:'EiC invited paper · ESI Highly Cited Paper' },
  { year:'2020', title:'环境扰动约束下的稀疏贝叶斯定位方法', venue:'声学学报, vol. 45, no. 4, pp. 475–485' },
  { year:'2019', title:'Exploiting Transmission Control for Joint User Identification and Channel Estimation in Massive Connectivity', venue:'IEEE Transactions on Communications, vol. 67, no. 9, pp. 6311–6326' },
  { year:'2019', title:'NOMA for Hybrid mmWave Communication Systems with Beamwidth Control', venue:'IEEE Journal of Selected Topics in Signal Processing, vol. 13, no. 3, pp. 567–583' },
  { year:'2019', title:'Multi-Beam NOMA for Hybrid mmWave Systems', venue:'IEEE Transactions on Communications, vol. 67, no. 2, pp. 1705–1719' },
  { year:'2018', title:'Multi-cell Hybrid Millimeter Wave Systems: Pilot Contamination and Interference Mitigation', venue:'IEEE Transactions on Communications, vol. 66, no. 11, pp. 5740–5755' },
  { year:'2018', title:'Joint Pilot and Payload Power Control for Uplink MIMO-NOMA with MRC-SIC Receivers', venue:'IEEE Communications Letters, vol. 22, no. 4, pp. 692–695' },
  { year:'2017', title:'Optimal Resource Allocation for Power-Efficient MC-NOMA with Imperfect Channel State Information', venue:'IEEE Transactions on Communications, vol. 65, no. 9, pp. 3944–3961', note:'ESI Highly Cited Paper' },
  { year:'2016', title:'A Survey of Downlink Non-orthogonal Multiple Access for 5G Wireless Communication Networks', venue:'ZTE Communications, vol. 14, no. 4, pp. 17–25', note:'Invited paper' },
  { year:'2014', title:'单指向性水听器及其在波束形成中的应用', venue:'声学技术, no. 6, pp. 572–576' },
  { year:'2014', title:'单指向水听器以及双圈十元阵的实验研究', venue:'电声技术, vol. 38, no. 1, pp. 73–74, 78' },
];

export const conferencePublications: Publication[] = [
  { year:'2026', title:'A Novel Iterative OTFS Detector Based on Local L-MMSE and Global Message Passing', venue:'IEEE ICASSP 2026, Barcelona, pp. 21501–21505' },
  { year:'2026', title:'CKM Beyond Channel Gain: Spatial Correlation Map Construction with Deep Learning', venue:'IEEE WCNC 2026, Kuala Lumpur, pp. 1–6', href:'https://wcnc2026.ieee-wcnc.org/ieee-wireless-communications-and-networking-conference-21/events/mlo-3-data-driven-modeling-and' },
  { year:'2025', title:'LANM: Learned Atomic Norm Minimization for Superfast Gridless Spectral Compressed Sensing', venue:'IEEE MLSP 2025, Istanbul, pp. 1–6' },
  { year:'2025', title:'A Fractional Programming Approach for the Joint Optimization of Communication Performance and Detection Probability', venue:'8th International Conference on Information Communication and Signal Processing, pp. 844–848' },
  { year:'2024', title:'Analysis of Cross-Domain Message Passing for OTFS Transmissions', venue:'IEEE Information Theory Workshop, pp. 424–429' },
  { year:'2024', title:'Rate-Distortion Tradeoff of Bistatic Integrated Sensing and Communication', venue:'IEEE Information Theory Workshop, pp. 360–365' },
  { year:'2024', title:'Fast Spatio-Temporal Signal Recovery Based on Differential Smoothness Regularization', venue:'IEEE International Conference on Signal, Information and Data Processing, pp. 1–6' },
  { year:'2024', title:'Wideband Direction-of-Arrival Estimation via Covariance Fitting and Focusing', venue:'EUSIPCO, pp. 2282–2286' },
  { year:'2024', title:'Closed-Form Outage Probability Analysis for OTFS-Based Multi-Beam LEO Satellites', venue:'IEEE/CIC ICCC, pp. 769–773' },
  { year:'2024', title:'Secure OTFS Transmission via Joint Delay-Doppler Precoding and Time-Domain Noise Injection', venue:'IEEE/CIC ICCC, pp. 569–574' },
  { year:'2024', title:'Optimal BER Minimum Precoder Design for OTFS-Based ISAC Systems', venue:'IEEE ICASSP, pp. 1–7' },
  { year:'2024', title:'Beamforming Design for RIS-Aided MIMO Communication: A Piece-Wise Near-Field Model', venue:'IEEE/CIC ICCC, pp. 1–6' },
  { year:'2023', title:'Channel Estimation for RIS-Aided MIMO Systems via Partially Decoupled Atomic Norm Minimization', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2023', title:'SDR System Design and Implementation on Delay-Doppler Communications and Sensing', venue:'IEEE WCNC, pp. 1–6' },
  { year:'2023', title:'Near Optimal Hybrid Digital-Analog Beamforming for Point-to-Point MIMO-OTFS Transmissions', venue:'IEEE WCNC, pp. 1–6', note:'Best Paper Award' },
  { year:'2023', title:'Source Localization for Constant Modulus Signals Using a Structured Matrix Recovery Technique (SMART)', venue:'IEEE Statistical Signal Processing Workshop, pp. 175–179' },
  { year:'2023', title:'Sensing-Enhanced Secure Communication: Joint Time Allocation and Beamforming Design', venue:'International Symposium on Modeling and Optimization in Mobile, Ad Hoc, and Wireless Networks, pp. 673–680' },
  { year:'2023', title:'On the Pulse Shaping for Delay-Doppler Communications', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2022', title:'Safeguarding UAV Networks Through Integrated Sensing, Jamming, and Communications', venue:'IEEE ICASSP, pp. 1–7' },
  { year:'2022', title:'Beamforming Design for Intelligent Reflecting Surface-Enhanced Symbiotic Radio Systems', venue:'IEEE ICC, pp. 1–6' },
  { year:'2022', title:'Trajectory Design and Resource Allocation for UAV-Enabled Data Collection in Wireless Sensor Networks with 3D Blockages', venue:'IEEE International Conference on 6G Networking, pp. 1–8' },
  { year:'2021', title:'A New Off-Grid Channel Estimation Method with Sparse Bayesian Learning for OTFS Systems', venue:'IEEE GLOBECOM, pp. 1–7' },
  { year:'2021', title:'Performance Analysis and Window Design for Channel Estimation of OTFS Modulation', venue:'IEEE ICC, pp. 1–6' },
  { year:'2021', title:'On the Achievable Rates of Uplink NOMA with Asynchronized Transmission', venue:'IEEE WCNC, pp. 1–6' },
  { year:'2021', title:'Bypassing Channel Estimation for OTFS Transmission: An Integrated Sensing and Communication Solution', venue:'IEEE WCNC, pp. 1–6' },
  { year:'2021', title:'Deep Learning-Empowered Predictive Beamforming for IRS-Assisted Multi-User Communications', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2021', title:'Secrecy Outage-Constrained Robust Resource Allocation Design for MU-MISO RSMA Systems', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2021', title:'A Tutorial to Orthogonal Time Frequency Space Modulation for Future Wireless Communications', venue:'IEEE/CIC ICCC, pp. 1–6' },
  { year:'2021', title:'On the Performance of Coded OTFS Modulation over High-Mobility Channels', venue:'IEEE ICC, pp. 1–6' },
  { year:'2021', title:'Deep Reinforcement Learning-Based Spectrum Allocation and Power Management for IAB Networks', venue:'IEEE ICC, pp. 1–6' },
  { year:'2020', title:'Sum-Rate Maximization for IRS-Assisted UAV OFDMA Communication Systems', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2020', title:'Sum-Rate Maximization for Multiuser MISO Downlink Systems with Self-Sustainable IRS', venue:'IEEE GLOBECOM, pp. 1–7' },
  { year:'2020', title:'Resource Allocation for Power-Efficient IRS-Assisted UAV Communications', venue:'IEEE ICC, pp. 1–7' },
  { year:'2020', title:'Deep Transfer Learning-Assisted Signal Detection for Ambient Backscatter Communications', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2019', title:'A Two-Stage Beam Alignment Framework for Hybrid mmWave Distributed Antenna Systems', venue:'IEEE SPAWC, pp. 1–6' },
  { year:'2019', title:'Beamwidth Control for NOMA in Hybrid mmWave Communication Systems', venue:'IEEE ICC, pp. 1–6' },
  { year:'2019', title:'Energy-Efficient Resource Allocation for Secure UAV Communication Systems', venue:'IEEE WCNC, pp. 1–8' },
  { year:'2019', title:'Deep Learning Assisted User Identification in Massive Machine-Type Communications', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2019', title:'A Distributed Multi-RF Chain Hybrid mmWave Scheme for Small-Cell Systems', venue:'IEEE ICC, pp. 1–7' },
  { year:'2018', title:'On the Performance Gain of NOMA over OMA in Uplink Single-Cell Systems', venue:'IEEE GLOBECOM, pp. 1–7' },
  { year:'2018', title:'A Multi-Beam NOMA Framework for Hybrid mmWave Systems', venue:'IEEE ICC, pp. 1–7', note:'Best Paper Award' },
  { year:'2018', title:'Joint Trajectory and Resource Allocation Design for UAV Communication Systems', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2018', title:'Mitigating Pilot Contamination in Multi-Cell Hybrid Millimeter Wave Systems', venue:'IEEE ICC, pp. 1–7' },
  { year:'2018', title:'Joint User Identification and Channel Estimation in Massive Connectivity with Transmission Control', venue:'IEEE International Symposium on Turbo Codes & Iterative Information Processing, pp. 1–6' },
  { year:'2018', title:'Physical-Layer Secure Transmissions in Cache-Enabled Cooperative Small Cell Networks', venue:'IEEE GLOBECOM, pp. 1–6' },
  { year:'2017', title:'Fairness Comparison of Uplink NOMA and OMA', venue:'IEEE VTC, pp. 1–6' },
  { year:'2017', title:'Performance Analysis of a Hybrid Downlink-Uplink Cooperative NOMA Scheme', venue:'IEEE VTC, pp. 1–7' },
  { year:'2016', title:'Power-Efficient Resource Allocation for MC-NOMA with Statistical Channel State Information', venue:'IEEE GLOBECOM, pp. 1–7' },
];
